### ISSUE TITLE
Make ruby 2.6 optional

### ISSUE THREAD

**Issue by slayer** [olegantonyan/typerb#3]
I sure that requirements for ruby-2.6 can be optional. Especially for dynamic languages like Ruby.

**Comment by olegantonyan** [comment]
Possible, but we'll loose an ability to get variable name. Might not be crucial though

**Comment by olegantonyan** [comment]
https://github.com/olegantonyan/typerb/pull/4 ugly shit

**Comment by slayer** [comment]
Not so ugly )

**Comment by olegantonyan** [comment]
done
